# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 210)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(30, 20, 341, 20))
        self.output.setAcceptDrops(False)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.caps = QtWidgets.QCheckBox(self.centralwidget)
        self.caps.setGeometry(QtCore.QRect(30, 60, 111, 17))
        self.caps.setObjectName("caps")
        self.special_char = QtWidgets.QCheckBox(self.centralwidget)
        self.special_char.setGeometry(QtCore.QRect(30, 120, 151, 17))
        self.special_char.setObjectName("special_char")
        self.num = QtWidgets.QCheckBox(self.centralwidget)
        self.num.setGeometry(QtCore.QRect(30, 90, 101, 17))
        self.num.setObjectName("num")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 90, 81, 16))
        self.label.setObjectName("label")
        self.min_length = QtWidgets.QComboBox(self.centralwidget)
        self.min_length.setGeometry(QtCore.QRect(310, 90, 41, 22))
        self.min_length.setObjectName("min_length")
        self.min_length.addItem("")
        self.min_length.addItem("")
        self.min_length.addItem("")
        self.min_length.addItem("")
        self.min_length.addItem("")
        self.min_length.addItem("")
        self.min_length.addItem("")
        self.min_length.addItem("")
        self.min_length.addItem("")
        self.min_length.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 120, 91, 16))
        self.label_2.setObjectName("label_2")
        self.max_length = QtWidgets.QComboBox(self.centralwidget)
        self.max_length.setGeometry(QtCore.QRect(310, 120, 41, 22))
        self.max_length.setObjectName("max_length")
        self.max_length.addItem("")
        self.max_length.addItem("")
        self.max_length.addItem("")
        self.max_length.addItem("")
        self.max_length.addItem("")
        self.max_length.addItem("")
        self.max_length.addItem("")
        self.max_length.addItem("")
        self.gen_button = QtWidgets.QPushButton(self.centralwidget)
        self.gen_button.setGeometry(QtCore.QRect(30, 160, 91, 23))
        self.gen_button.setObjectName("gen_button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 60, 81, 16))
        self.label_3.setObjectName("label_3")
        self.word_count = QtWidgets.QComboBox(self.centralwidget)
        self.word_count.setGeometry(QtCore.QRect(310, 60, 41, 22))
        self.word_count.setObjectName("word_count")
        self.word_count.addItem("")
        self.word_count.addItem("")
        self.word_count.addItem("")
        self.word_count.addItem("")
        self.word_count.addItem("")
        self.word_count.addItem("")
        self.word_count.addItem("")
        self.word_count.addItem("")
        self.word_count.addItem("")
        self.word_count.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Passgen"))
        self.caps.setText(_translate("MainWindow", "Capitalized Words"))
        self.special_char.setText(_translate("MainWindow", "Append Special Character"))
        self.num.setText(_translate("MainWindow", "Append Number"))
        self.label.setText(_translate("MainWindow", "Min Word Length"))
        self.min_length.setItemText(0, _translate("MainWindow", "1"))
        self.min_length.setItemText(1, _translate("MainWindow", "2"))
        self.min_length.setItemText(2, _translate("MainWindow", "3"))
        self.min_length.setItemText(3, _translate("MainWindow", "4"))
        self.min_length.setItemText(4, _translate("MainWindow", "5"))
        self.min_length.setItemText(5, _translate("MainWindow", "6"))
        self.min_length.setItemText(6, _translate("MainWindow", "7"))
        self.min_length.setItemText(7, _translate("MainWindow", "8"))
        self.min_length.setItemText(8, _translate("MainWindow", "9"))
        self.min_length.setItemText(9, _translate("MainWindow", "10"))
        self.label_2.setText(_translate("MainWindow", "Max Word Length"))
        self.max_length.setItemText(0, _translate("MainWindow", "3"))
        self.max_length.setItemText(1, _translate("MainWindow", "4"))
        self.max_length.setItemText(2, _translate("MainWindow", "5"))
        self.max_length.setItemText(3, _translate("MainWindow", "6"))
        self.max_length.setItemText(4, _translate("MainWindow", "7"))
        self.max_length.setItemText(5, _translate("MainWindow", "8"))
        self.max_length.setItemText(6, _translate("MainWindow", "9"))
        self.max_length.setItemText(7, _translate("MainWindow", "10"))
        self.gen_button.setText(_translate("MainWindow", "Generate"))
        self.label_3.setText(_translate("MainWindow", "Word Count"))
        self.word_count.setItemText(0, _translate("MainWindow", "1"))
        self.word_count.setItemText(1, _translate("MainWindow", "2"))
        self.word_count.setItemText(2, _translate("MainWindow", "3"))
        self.word_count.setItemText(3, _translate("MainWindow", "4"))
        self.word_count.setItemText(4, _translate("MainWindow", "5"))
        self.word_count.setItemText(5, _translate("MainWindow", "6"))
        self.word_count.setItemText(6, _translate("MainWindow", "7"))
        self.word_count.setItemText(7, _translate("MainWindow", "8"))
        self.word_count.setItemText(8, _translate("MainWindow", "9"))
        self.word_count.setItemText(9, _translate("MainWindow", "10"))

